name: h2o
channels:
  - defaults
  - conda-forge
dependencies:
  - h2o 
  - tensorflow-gpu=1.12.0 
  - tensorflow-hub 
  - keras=2.2.4 
  - pandas=0.24.1 
  - pyyaml=3.13 
  - scikit-learn=0.20.2 
  - matplotlib 
  - jupyter 
  - jupyterlab
